// User Login
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";

// User Register
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

// Restaurant Login
export const LOGIN_RESTAURANT = "LOGIN_RESTAURANT";
export const LOGIN_RESTAURANT_ERROR = "LOGIN_RESTAURANT_ERROR";
export const LOGOUT_RESTAURANT = "LOGOUT_RESTAURANT";

// Restaurant Logout
export const REGISTER_RESTAURANT = "REGISTER_RESTAURANT";
export const REGISTER_RESTAURANT_ERROR = "REGISTER_RESTAURANT_ERROR";

// Cart
export const GET_CART_COUNT = "GET_CART_COUNT";

// User Preferences
export const SET_USER_DELIVERY_TYPE = "SET_USER_DELIVERY_TYPE";
export const SET_USER_LOCATION = "SET_USER_LOCATION";

// Dish
export const ADD_DISH = "ADD_DISH";
export const ADD_DISH_ERROR = "ADD_DISH_ERROR";
export const UPDATE_DISH = "UPDATE_DISH";
export const UPDATE_DISH_ERROR = "UPDATE_DISH_ERROR";
export const DISHES_BY_RESTAURANT = "DISHES_BY_RESTAURANT";
export const DISHES_BY_RESTAURANT_ERROR = "DISHES_BY_RESTAURANT_ERROR";
export const DISH_CATEGORIES = "DISH_CATEGORIES";
export const DISH_CATEGORIES_ERROR = "DISH_CATEGORIES_ERROR";

// Restaurant
export const RESTAURANT_DETAILS = "RESTAURANT_DETAILS";
export const RESTAURANT_DETAILS_ERROR = "RESTAURANT_DETAILS_ERROR";
export const ALL_RESTAURANTS = "ALL_RESTAURANTS";
export const ALL_RESTAURANTS_ERROR = "ALL_RESTAURANTS_ERROR";

// Order
export const ORDER_DELIVERY_STATUS = "ORDER_DELIVERY_STATUS";
export const ORDER_DELIVERY_STATUS_ERROR = "ORDER_DELIVERY_STATUS_ERROR";
export const ORDERS_BY_RESTAURANT_ID = "ORDERS_BY_RESTAURANT_ID";
export const ORDERS_BY_RESTAURANT_ID_ERROR = "ORDERS_BY_RESTAURANT_ID_ERROR";
export const FILTERED_ORDERS_BY_RESTAURANT_ID =
  "FILTERED_ORDERS_BY_RESTAURANT_ID";
export const FILTERED_ORDERS_BY_RESTAURANT_ID_ERROR =
  "FILTERED_ORDERS_BY_RESTAURANT_ID_ERROR";
export const FILTERED_ORDERS_BY_USER_ID = "FILTERED_ORDERS_BY_USER_ID";
export const FILTERED_ORDERS_BY_USER_ID_ERROR =
  "FILTERED_ORDERS_BY_USER_ID_ERROR";
export const ORDER_DETAILS_BY_ID = "ORDER_DETAILS_BY_ID";
export const ORDER_DETAILS_BY_ID_ERROR = "ORDER_DETAILS_BY_ID_ERROR";
export const ORDERS_BY_USER_ID = "ORDERS_BY_USER_ID";
export const ORDERS_BY_USER_ID_ERROR = "ORDERS_BY_USER_ID_ERROR";
export const PLACE_ORDER = "PLACE_ORDER";
export const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR";

// User
export const USER_DETAILS = "USER_DETAILS";
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const ADD_TO_FAVOURITE_ERROR = "ADD_TO_FAVOURITE_ERROR";
export const GET_USER_FAVOURITES = "GET_USER_FAVOURITES";
export const GET_USER_FAVOURITES_ERROR = "GET_USER_FAVOURITES_ERROR";
export const USER_ADDRESSES = "USER_ADDRESSES";
export const USER_ADDRESSES_ERROR = "USER_ADDRESSES_ERROR";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const ADD_ADDRESS_ERROR = "ADD_ADDRESS_ERROR";
